### ISSUE TITLE
rocket_clean_domain_for_all_langs and run_rocket_bot_for_all_langs is deprecated

### ISSUE THREAD

**Issue by djaevlen** [GeekPress/wp-rocket-cli#12]
Hi there,

Running the latest WP-rocket gives a warning when executing the `wp rocket clean` and `wp rocket preload` command.

`wp rocket clean`
`Notice: rocket_clean_domain_for_all_langs is <strong>deprecated</strong> since version 2.2! Use rocket_clean_domain() instead. in /wp-includes/functions.php on line 3828`

`wp rocket preload`
`Notice: run_rocket_bot_for_all_langs is <strong>deprecated</strong> since version 2.2! Use run_rocket_bot() instead. in /wp-includes/functions.php on line 3828`

Im running with Polylang with 6 languages.

**Comment by mihdan** [comment]
https://github.com/GeekPress/wp-rocket-cli/pull/16
