### ISSUE TITLE
A simple CLEAN command generates a PHP Fatal Error

### ISSUE THREAD

**Issue by jfarsen** [GeekPress/wp-rocket-cli#17]
I installed the CLI package, and ran the simple command `wp rocket clean` and received a PHP Fatal Error, as follows : 

`wp rocket clean`
`Delete all cache files ? [y/n] y`
`Fatal error: Uncaught Error: Call to undefined function rocket_clean_domain_for_all_langs() in /home/<client>/.wp-cli/packages/vendor/GeekPress/wp-rocket-cli/command.php:226`
`Stack trace:`
`#0 [internal function]: WPRocket_CLI->clean(Array, Array)`
`#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)`
`#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)`
`#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)`
`#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(360): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)`
`#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(383): WP_CLI\Runner->run_command(Array, Array)`
`#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1109): WP_CLI\Runner->_run_command_and_exit()`
`#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()`
`#8 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootst in /home/<client>/.wp-cli/packages/vendor/GeekPress/wp-rocket-cli/command.php on line 226`

**Comment by renecum** [comment]
I have the same problem

**Comment by GeekPress** [comment]
It has been fixed with the new 1.1.1 version.
