### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function run_rocket_bot_for_all_langs()

### ISSUE THREAD

**Issue by fhfournier** [GeekPress/wp-rocket-cli#19]
Last version of WP-CLI i got this error when trying to use "wp rocket preload"

www-data@rdvcanada:~/rdvcanada.ca/htdocs$ wp rocket preload
PHP Fatal error:  Uncaught Error: Call to undefined function run_rocket_bot_for_all_langs() in /var/www/.wp-cli/packages/vendor/GeekPress/wp-rocket-cli/command.php:249
Stack trace:
#0 [internal function]: WPRocket_CLI->preload(Array, Array)
#1 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1132): WP_CLI\Runner->run_command_and_exit()
#7 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\ in /var/www/.wp-cli/packages/vendor/GeekPress/wp-rocket-cli/command.php on line 249
Fatal error: Uncaught Error: Call to undefined function run_rocket_bot_for_all_langs() in /var/www/.wp-cli/packages/vendor/GeekPress/wp-rocket-cli/command.php:249
Stack trace:
#0 [internal function]: WPRocket_CLI->preload(Array, Array)
#1 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1132): WP_CLI\Runner->run_command_and_exit()
#7 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\ in /var/www/.wp-cli/packages/vendor/GeekPress/wp-rocket-cli/command.php on line 249

**Comment by GeekPress** [comment]
Fixed with 1.1.2
