### ISSUE TITLE
Create a release for 1.1

### ISSUE THREAD

**Issue by anugupta** [GeekPress/wp-rocket-cli#4]
We're going to be using this as part of our deployment process - is there any chance you can create a release for 1.1, so that we have a fixed version to point to?

**Comment by GeekPress** [comment]
Hi,

I'm not sure to understand what you are asking. Why should I create a new release 1.1? 

Cheers

**Comment by anugupta** [comment]
Hey Jonathon - it was nice to meet you yesterday.

On this project, my client's team would like to control the deployment - and deploy fixed versions of each piece of software. If there is a version 1.1, we can pull exactly that version and deploy it, knowing that it has been tested and works fine. Otherwise we would pull HEAD, and changes that are made might break the build

I hope this makes sense - hopefully it's not too much trouble!

Thanks

**Comment by Biont** [comment]
Same here. I could make good use of the `regenerate` command in a project, but do not feel comfortable pulling the master as part of our deployment. A 1.1 release would solve that, so please consider it

**Comment by GeekPress** [comment]
A 1.1.1 release has just been published.
