### ISSUE TITLE
Add `import` and `export` commands

### ISSUE THREAD

**Issue by GeekPress** [GeekPress/wp-rocket-cli#45]
**Describe the solution you'd like**
We can import and export WP Rocket settings from the Tools tab of the plugin settings page.

To provide a better automation solution, it could be useful to have the same actions possible with CLI:
`wp rocket import` and `wp rocket export`

**Comment by Basilakis** [comment]
Related #18

**Comment by Basilakis** [comment]
@GeekPress Has PR ;-)

**Comment by GeekPress** [comment]
@Basilakis Thanks a lot for the PR :)

@Tabrisrp FYI 👆

**Comment by Basilakis** [comment]
@Tabrisrp We appreciate your time on validating this.

**Comment by Basilakis** [comment]
@Tabrisrp Could you please take a look?

**Comment by remyperona** [comment]
@Basilakis I will, I have it on my to-do list 👍🏼
